Repository xihai01/Pandemic-Tracker, pull requests merged in 2022-01, with the labels that each got.

#6 Storybook/health region component
  client/.storybook/addons.js
  client/.storybook/config.js
  client/.storybook/main.js
  client/.storybook/preview.js
  client/.storybook/webpack.config.js
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/components/HealthRegion.css
  client/src/components/HealthRegion.js
  client/src/components/HealthRegionList.js
  client/src/helpers/handleZoom.js
  client/src/hooks/useApplicationData.js
  client/src/hooks/useInitialize.js
  client/src/index.css
  client/src/reducer/data_reducer.js
  client/src/stories/index.js
  server/Gemfile.lock
  server/app/assets/javascripts/api/maps.coffee
  server/app/assets/stylesheets/api/maps.scss
  server/app/controllers/api/maps_controller.rb
  server/app/controllers/application_controller.rb
  server/app/helpers/api/maps_helper.rb
  server/app/models/health_region.rb
  server/app/models/stage.rb
  server/app/models/stage_one_restriction.rb
  server/app/models/stage_three_restriction.rb
  server/app/models/stage_two_restriction.rb
  server/config/routes.rb
  server/db/migrate/20220115222752_create_stage_one_restrictions.rb
  server/db/migrate/20220115222812_create_stage_two_restrictions.rb
  server/db/migrate/20220115222823_create_stage_three_restrictions.rb
  server/db/migrate/20220118040235_add_stage_id_to_health_regions.rb
  server/db/migrate/20220118040714_create_stages.rb
  server/db/schema.rb
  server/db/seeds.rb
Labels: enhancement

#11 Feature/stage color
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/HealthRegion.css
  client/src/components/HealthRegion.js
  client/src/components/HealthRegionList.js
  client/src/hooks/useApplicationData.js
  client/src/hooks/useInitialize.js
  client/src/reducer/data_reducer.js
  server/.rspec
  server/Gemfile
  server/Gemfile.lock
  server/app/controllers/api/map_color_controller.rb
  server/config/routes.rb
  server/db/seeds.rb
  server/spec/models/health_region_spec.rb
  server/spec/rails_helper.rb
  server/spec/spec_helper.rb
Labels: bug, enhancement

#16 Admin/pages
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/components/Admin.jsx
  client/src/components/admin/AdminBoard.jsx
  client/src/components/admin/AdminLogin.jsx
  client/src/index.js
  client/src/reducer/admin_reducer.js
Labels: enhancement

#25 fix/dashboard
  client/src/components/admin/AdminBoard.js
  client/src/components/admin/AdminLogin.js
  client/src/components/admin/dashboard/AdminBoard.jsx
Labels: bug

#31 Feature/boardupdates
  client/2022-01-25-06-48-05.050-VBoxHeadless-9158.log
  client/src/components/admin/dashboard/HealthTable.jsx
  client/src/components/admin/dashboard/Stages.jsx
  client/src/hooks/useHealthData.js
  client/src/hooks/useStagesData.js
  server/app/controllers/admin/health_regions_controller.rb
  server/app/controllers/admin/stages_controller.rb
  server/app/controllers/application_controller.rb
  server/config/routes.rb
Labels: enhancement

#32 close missing bracket
  client/public/images/undraw_server_down_s-4-lk.svg
  client/public/undraw_server_down_s-4-lk.svg
  client/src/App.css
  client/src/components/admin/AdminLogin.js
  client/src/components/admin/dashboard/AdminBoard.jsx
Labels: bug

#33 Style/map layout
  client/public/images/ceremony.jpg
  client/public/images/entertainment.png
  client/public/images/indoor.jpeg
  client/public/images/location.jpg
  client/public/images/outdoor.jpg
  client/public/images/personalcare.jpeg
  client/public/images/retail.jpg
  client/public/images/sports.jpg
  client/public/images/test.jpeg
  client/public/index.html
  client/src/App.css
  client/src/components/DisplayRestrictions.js
  client/src/components/HealthRegion.css
  client/src/components/HealthRegionList.js
  client/src/components/LegendAndCovidStats.js
  client/src/components/Nav.js
  client/src/components/Navbar.js
  client/src/index.js
  server/app/controllers/api/restrictions_controller.rb
Labels: enhancement

#36 Update/readme.md
  README.md
  docs/admin.png
  docs/app.jpeg
  docs/app.png
  docs/erd.png
  docs/interactive-map.gif
Labels: documentation

#39 update README.md with pics and gifs
  README.md
Labels: documentation
